### ISSUE TITLE
Error Build MAC M1

### ISSUE THREAD

**Issue by MrSpock182** [aws/serverless-java-container#1209]
Using the usually process on Macbook M1 PRO

Mac OS 15.1.1

After execute the command
docker run -it -v `pwd`:`pwd` -w `pwd` -v ~/.m2:/root/.m2 al2023-graalvm21:native-web ./mvnw clean -Pnative package -DskipTests

The result is 'rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2'

**Comment by deki** [comment]
Hi @MrSpock182,
the sample is for x86. In case you want to build and run it on ARM, you must change the according line in the `Dockerfile` to `ENV ARCHITECTURE aarch64`. In addition, uncomment the `arm64` Architectures section in `template.yml`. 

Added a note to the readme as well.
