### ISSUE TITLE
[RFC] Support for native-image compilation

### ISSUE THREAD

**Issue by sapessi** [aws/serverless-java-container#335]
* Implementations: Spring 5.3.x / Spring Boot 2

## Scenario
As the Spring framework adds support for [GraalVM's native image tool](https://github.com/spring-projects/spring-framework/wiki/GraalVM-native-image-support), we should explore making it easy to compile SpringBoot applications and execute them as a custom runtime in AWS Lambda

This issue serves as a tracker for this project to make design decisions and collect feedback on the implementation

**Comment by urmichm** [comment]
Totally support this issue!
@sapessi if you are interested I might help to create a project for GraalVM and Springboot with MVC controllers.
Please, let me know if you have a plan regarding this issue :)

**Comment by deki** [comment]
Please check https://catalog.workshops.aws/java-on-aws-lambda/en-US/01-migration/03-alternatives/graalvm for an example. Will get that added to the docs.

**Comment by fsomme2s** [comment]
Now that we have Spring Boot 3 Support (see #487, which I tested and it works really nice so far! Awesome work!), maybe it's time to revive this issue? 

I can use Spring Boot Native to create Custom Images; I can use the serverless-java-container lib to "bridge" Api Gateway Events into Spring ... But I can't get my head around how to combine these two.

Is this already possible? Or would it need some kind of special Custom Runtime "Event Loop" thing, similar to [this](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/CustomRuntimeEventLoop.java) ? (That would call SpringBootLambdaContainerHandler.proxy(...) when it polls a new event)

**Comment by babaksd** [comment]
I'm having trouble integrating aws-serverless-java-container-springboot3 with Graalvm and a custom lambda runtime/handler. Has anyone successfully managed to do this? Is the anyway to make it work?

**Comment by deki** [comment]
Hey @babaksd, we are aware. @olegz is currently working on that and we'll include it in the next release (current plan is to have that end of this month).

**Comment by babaksd** [comment]
@deki That's great, Thank you for the amazing work!

**Comment by deki** [comment]
#739 has been merged and will be part of the next release. We've also added a sample: https://github.com/aws/serverless-java-container/tree/main/samples/springboot3/pet-store-native
