### ISSUE TITLE
: Could not initialize class com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler

### ISSUE THREAD

**Issue by anandv1770** [aws/serverless-java-container#405]
Hi Stefano, Thanks for the great presentation.  I followed the instructions as per Readme.txt(sample/springboot2/native-pet-store)  and I'm able to deploy as Lambda but when I invoke the URL I get Internal server error and could see following error in Cloud watch logs:  Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler, Request you to kindly help me to fix this issue ASAP.

**Comment by sapessi** [comment]
Looks like the class you need is not getting packaged in the deployment or something is not trying to load the right class. The native project should depend on the `com.amazonaws.serverless.proxy.springboot2` package.

**Comment by anandv1770** [comment]
> Looks like the class you need is not getting packaged in the deployment or something is not trying to load the right class. The native project should depend on the `com.amazonaws.serverless.proxy.springboot2` package.

   Thanks for the quick response I did not make any changes , just followed the steps mentioned in README under sample/springboot2/native-pet-store  :(. Please suggest. Should I make any changes in configuration or its ok to use as is?

**Comment by anandv1770** [comment]
I request you to kindly help us on this ASAP. Stuck with cold start spring boot cloud function even for a simple hello world and company has decided to go ahead with aws lambda for all rest calls :(

**Comment by deki** [comment]
@anandv1770 are you still stuck? happy to help...

**Comment by deki** [comment]
No further feedback, closing...
