### ISSUE TITLE
Investigate why latest maven-archetype-plugin breaks release build

### ISSUE THREAD

**Issue by deki** [aws/serverless-java-container#563]
Release build fails with maven-archetype-plugin 3.2.1. I had to downgrade to 3.0.1 for a successful build.

Use a dry run (`mvn release:prepare -DdryRun=true`) to reproduce and consider reporting here https://maven.apache.org/archetype/maven-archetype-plugin/issue-management.html in case no solution is available.

**Comment by mbfreder** [comment]
Not getting any error when running `mvn release:prepare -DdryRun=true`. @deki does the release build still fail on your side?
<img width="1434" alt="Screenshot 2023-11-20 at 9 23 40 PM" src="https://github.com/awslabs/aws-serverless-java-container/assets/117131783/ca4bccfd-6e43-4435-9b95-fe1964dc2c69">

**Comment by deki** [comment]
Yes, the issue still exists. Did you update the maven-archetype-plugin in `aws-serverless-jersey-archetype/pom.xml`, `aws-serverless-spring-archetype/pom.xml` and `aws-serverless-struts-archetype/pom.xml`?

**Comment by mbfreder** [comment]
I updated  in `maven-archetype-plugin`' to 3.2.1 in `aws-serverless-jersey-archetype/pom.xml`, `aws-serverless-spring-archetype/pom.xml` and `aws-serverless-springboot3-archetype/pom.xml`. I'm not getting any error. Is there anything else I can do to reproduce?

**Comment by deki** [comment]
Maybe a fresh clone on EC2? I saw it in the GitHub runner logs and I can reproduce it both on a Mac and on a Windows machine.

**Comment by deki** [comment]
Fixed as part of the 2.1.0 release.
