### ISSUE TITLE
"java.lang.NoClassDefFoundError" on Pet Store sample project

### ISSUE THREAD

**Issue by Neves97** [aws/serverless-java-container#749]
I downloaded the SpringBoot3 Pet-store demo project from this repository  (https://github.com/aws/serverless-java-container/tree/main/samples/springboot3/pet-store)

I opened it as a Gradle project in IntelliJ and then executed the "gradle clean build" command to generate the JAR file **pet-store.jar**.

Then, I uploaded the file to my Lambda on the AWS Lambda Console (without using SAM). The handler is configured to call **com.amazonaws.serverless.sample.springboot3.StreamLambdaHandler::handleRequest** which is the same as specified in the template.yml file.

The project is configured to use Java 17 (corretto).

Upon invoking the function, the following error message appears in CloudWatch:

`Error loading class com.amazonaws.serverless.sample.springboot3.StreamLambdaHandler: com/amazonaws/serverless/exceptions/ContainerInitializationException: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/amazonaws/serverless/exceptions/ContainerInitializationException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.serverless.exceptions.ContainerInitializationException
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more`

Despite the error, the function returns a 200 status code along with the following message:

`{
	"errorMessage": "Error loading class com.amazonaws.serverless.sample.springboot3.StreamLambdaHandler: com/amazonaws/serverless/exceptions/ContainerInitializationException",
	"errorType": "java.lang.NoClassDefFoundError"
}`

Is there anything I might be forgetting? Is deploying via SAM CLI strictly necessary?
Thanks in advance!

**Comment by Neves97** [comment]
I builted a ZIP file using Maven, it seens to work!

**Comment by deki** [comment]
You can also use Gradle but need to use the `buildZip` task.

**Comment by Neves97** [comment]
That did the trick! Thank you!
