### ISSUE TITLE
Not able to apply spring security on pet-store-native sample

### ISSUE THREAD

**Issue by AniS-03** [aws/serverless-java-container#769]
*Serverless Java Container version*: `2.0.0`

*Implementations:* `Spring Boot 3`

*Framework version:* `SpringBoot 3.2.2`

*Frontend service:* `HTTP API`

*Deployment method:* `SAM`

## Scenario
*I was trying to add spring security filters in [pet-store-native](https://github.com/aws/serverless-java-container/tree/main/samples/springboot3/pet-store-native) sample application.*

## Expected behavior
*All the filters should run inside security filter chain and also authorising an endpoint should work normally.*

## Actual behavior
*Some filter are running out of security filter chain and request is still reaching to an endpoint even provided that request should be authenticated.*

## Steps to reproduce
*It can be reproduce by running this [demo](https://github.com/AniS-03/demo-aws-serverless-web-native-app) application using docker or on linux architecture as a native web app using sam-cli.*

## Full log output
![trace_logs](https://github.com/aws/serverless-java-container/assets/155950031/c50a2bb5-b15e-483b-b46a-d16a24394a0c)
![request](https://github.com/aws/serverless-java-container/assets/155950031/adceff19-8b76-4169-b8ba-4afcdee32d9f)

**Comment by olegz** [comment]
I don't see anywhere in your example configuration for `SecurityFilterChain`, something similar to
```
@Bean
public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
	http
	.addFilterBefore(new GenericFilterBean() {
		@Override
		public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
					throws IOException, ServletException {
			SecurityContext securityContext = SecurityContextHolder.getContext();
			securityContext.setAuthentication(UsernamePasswordAuthenticationToken.authenticated("user", "password",
					Collections.singleton(new SimpleGrantedAuthority("USER"))));
			HttpSession session = ((HttpServletRequest) request).getSession();
			session.setAttribute("SPRING_SECURITY_CONTEXT", securityContext);
				chain.doFilter(request, response);
		}
	}, SecurityContextHolderFilter.class)
	.securityMatcher("/foo")
	.authorizeHttpRequests(authorize -> authorize
			.anyRequest().hasRole("FOO")
		)
	.exceptionHandling(f -> f.accessDeniedHandler(accessDeniedHandler()));
	return http.build();
```
The example above is from one of the the cases to verify the security behavior - https://github.com/spring-cloud/spring-cloud-function/blob/0b08e8b242724287e15a2a193ad1ad1278d6c69e/spring-cloud-function-adapters/spring-cloud-function-serverless-web/src/test/java/org/springframework/cloud/function/test/app/PetStoreSpringAppConfig.java#L76

**Comment by olegz** [comment]
Yes, sorry about it, i noticed it and deleted my comment

**Comment by olegz** [comment]
Ok, I am a bit confused. Yes I do see two filters added to `SecurityFilterChain`. I also see from your screen shot (please use ASCII next time) that your filters are properly added and listed and executed in proper order.
However, non of them is doing any security related things to preclude any access and in addition your `authorizeHttpRequests`  basically invites all to `/pets`
```
.authorizeHttpRequests(auth -> {
                    auth
                            .requestMatchers("/pets").authenticated()
                            .anyRequest().permitAll();
                            // .anyRequest().permitAll();
                })
```

a simple modification to your code shows that everything works as expected
```
.addFilterAfter(new Filter() {			
	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
			throws IOException, ServletException {
					 throw new AccessDeniedException("Access denied"); 
		
	}
}, LogoutFilter.class)
. . .
```

Can you please clarify?

**Comment by AniS-03** [comment]
No actually from image I am trying to show that one of my security filter is running outside security filter chain. As you can see "Running a simple filter" is printed outside. But it should be printed after 
```2024-02-19T07:50:05.053Z TRACE 16 --- [pool-6-thread-1] o.s.security.web.FilterChainProxy        : Invoking SimpleFilter (8/13)```
Also even I have specified that `.requestMatchers("/pets").authenticated` which simple means request coming to `/pets` should be authenticated but as you can see from second image that I was able to access `/pets`, without providing anything for authentication.

**Comment by olegz** [comment]
Ok, I tracked it down. The issue is on my end with spring-cloud-function-web. I'll fix it but you would have to manually upgrade to the snapshot until the new release of serverless java container.
I'll also see if I can come up with a temporary workaround

**Comment by olegz** [comment]
See https://github.com/spring-cloud/spring-cloud-function/issues/1111

**Comment by AniS-03** [comment]
Ok so which version I need to try for spring-cloud-function?

**Comment by AniS-03** [comment]
@olegz could you please help me how to try the new version in my app?

**Comment by AniS-03** [comment]
@olegz thanks for help. It's working with 4.1.1-SNAPSHOT version of spring-cloud-function-serverless-web.
