### ISSUE TITLE
Stable version release for 2.x

### ISSUE THREAD

**Issue by vineet-ravi** [aws/serverless-java-container#882]
<img width="877" alt="Screenshot 2024-05-07 at 3 47 47 PM" src="https://github.com/aws/serverless-java-container/assets/38680794/8d79ef0c-67c8-4412-8878-ef5186ee30f1">
 When is the stable version for 2.x going to be released?
Currently, I'm using 2.x for java17 project which is under development. Any timelines for stable version?

I'm using following:
    implementation group: 'com.amazonaws.serverless', name: 'aws-serverless-java-container-core', version: '2.0.0-M2'
    implementation group: 'com.amazonaws.serverless', name: 'aws-serverless-java-container-spring', version: '2.0.0-M2'

**Comment by deki** [comment]
Both 1.x and 2.x are stable. Latest release is 2.0.1 as listed here: https://github.com/aws/serverless-java-container/releases
