### ISSUE TITLE
Moved AwsProxyRequestBuilder into test package

### ISSUE THREAD

**Issue by samburt0n5** [aws/serverless-java-container#887]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `eg. 1.5`
"com.amazonaws.serverless:aws-serverless-java-container-core:2.0.1"
*Implementations:* `Jersey / Spring / Spring Boot / Spring Boot 2 / Spark`

*Framework version:* `eg SpringBoot 2.2.6.RELEASE`

*Frontend service:* `REST API / HTTP API / ALB`

*Deployment method:* `eg SAM, Serverless Framework, Console`

## Scenario
Unit testing using com.amazonaws.serverless.proxy.internal.testutils.AwsProxyRequestBuilder
## Expected behavior

I would like to access this class in the dependency but it's not coming through.
## Actual behavior
The package com.amazonaws.serverless.proxy.internal.testutils now only contains "Timer"

## Steps to reproduce
*Provide code samples we can use to reproduce the issue as part of our integration tests. If there is a public repository for the misbehaving application link to it here*

## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

```
logs
```

**Comment by deki** [comment]
Please add the dependency like this and it should work:
```
        <dependency>
            <groupId>com.amazonaws.serverless</groupId>
            <artifactId>aws-serverless-java-container-core</artifactId>
            <version>2.0.1</version>
            <classifier>tests</classifier>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
```

**Comment by samburt0n5** [comment]
Thank you that worked. For reference in gradle it looks like the following
`    testImplementation("com.amazonaws.serverless:aws-serverless-java-container-core:2.0.1:tests")
`

**Comment by samburt0n5** [comment]
Apologies, this didn't actually work @deki . I'm now getting NoClassDefFoundError for some apache client5 library.
```
 "org/apache/hc/client5/http/entity/mime/ContentBody
java.lang.NoClassDefFoundError: org/apache/hc/client5/http/entity/mime/ContentBody"
```

Possibly due to this note found [here](https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html):
<img width="1641" alt="image" src="https://github.com/aws/serverless-java-container/assets/62301105/5c73d47a-38f3-45ae-9804-25c2942e7f98">

For now i can get away with adding the dependency manually myself but maybe consider the dependency needs adding [here](https://github.com/aws/serverless-java-container/blob/main/aws-serverless-java-container-core/pom.xml)?

**Comment by deki** [comment]
This dependency is already part of the POM but unfortunately Maven doesn't support transitive test dependencies for test-jars, see https://maven.apache.org/plugins/maven-jar-plugin/examples/create-test-jar.html:

> loose its transitive test-scoped dependencies

The alternative would be an own test module but so far we haven't seen the need for it.
